# generated from genmsg/cmake/pkg-msg-paths.cmake.develspace.in

set(spencer_social_relation_msgs_MSG_INCLUDE_DIRS "/home/az/github_may_messed_it_up_20250124arena_try_get_rel_vel_work/arena_ws/src/arena/utils/pedsim_ros/pedsim_engine/2ndparty/spencer_messages/spencer_social_relation_msgs/msg")
set(spencer_social_relation_msgs_MSG_DEPENDENCIES geometry_msgs;sensor_msgs;nav_msgs;std_msgs)
