// Generated by gencpp from file all_in_one_local_planner_interface/GetVelCmd.msg
// DO NOT EDIT!


#ifndef ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_GETVELCMD_H
#define ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_GETVELCMD_H

#include <ros/service_traits.h>


#include <all_in_one_local_planner_interface/GetVelCmdRequest.h>
#include <all_in_one_local_planner_interface/GetVelCmdResponse.h>


namespace all_in_one_local_planner_interface
{

struct GetVelCmd
{

typedef GetVelCmdRequest Request;
typedef GetVelCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVelCmd
} // namespace all_in_one_local_planner_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_in_one_local_planner_interface::GetVelCmd > {
  static const char* value()
  {
    return "374e901b019d93b77917983b7fa0d888";
  }

  static const char* value(const ::all_in_one_local_planner_interface::GetVelCmd&) { return value(); }
};

template<>
struct DataType< ::all_in_one_local_planner_interface::GetVelCmd > {
  static const char* value()
  {
    return "all_in_one_local_planner_interface/GetVelCmd";
  }

  static const char* value(const ::all_in_one_local_planner_interface::GetVelCmd&) { return value(); }
};


// service_traits::MD5Sum< ::all_in_one_local_planner_interface::GetVelCmdRequest> should match
// service_traits::MD5Sum< ::all_in_one_local_planner_interface::GetVelCmd >
template<>
struct MD5Sum< ::all_in_one_local_planner_interface::GetVelCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_in_one_local_planner_interface::GetVelCmd >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::GetVelCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_in_one_local_planner_interface::GetVelCmdRequest> should match
// service_traits::DataType< ::all_in_one_local_planner_interface::GetVelCmd >
template<>
struct DataType< ::all_in_one_local_planner_interface::GetVelCmdRequest>
{
  static const char* value()
  {
    return DataType< ::all_in_one_local_planner_interface::GetVelCmd >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::GetVelCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_in_one_local_planner_interface::GetVelCmdResponse> should match
// service_traits::MD5Sum< ::all_in_one_local_planner_interface::GetVelCmd >
template<>
struct MD5Sum< ::all_in_one_local_planner_interface::GetVelCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_in_one_local_planner_interface::GetVelCmd >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::GetVelCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_in_one_local_planner_interface::GetVelCmdResponse> should match
// service_traits::DataType< ::all_in_one_local_planner_interface::GetVelCmd >
template<>
struct DataType< ::all_in_one_local_planner_interface::GetVelCmdResponse>
{
  static const char* value()
  {
    return DataType< ::all_in_one_local_planner_interface::GetVelCmd >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::GetVelCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_GETVELCMD_H
