// Generated by gencpp from file all_in_one_local_planner_interface/ResetCostmap.msg
// DO NOT EDIT!


#ifndef ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_RESETCOSTMAP_H
#define ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_RESETCOSTMAP_H

#include <ros/service_traits.h>


#include <all_in_one_local_planner_interface/ResetCostmapRequest.h>
#include <all_in_one_local_planner_interface/ResetCostmapResponse.h>


namespace all_in_one_local_planner_interface
{

struct ResetCostmap
{

typedef ResetCostmapRequest Request;
typedef ResetCostmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetCostmap
} // namespace all_in_one_local_planner_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_in_one_local_planner_interface::ResetCostmap > {
  static const char* value()
  {
    return "c267a3b326f2460cbd8963b5e7db09b6";
  }

  static const char* value(const ::all_in_one_local_planner_interface::ResetCostmap&) { return value(); }
};

template<>
struct DataType< ::all_in_one_local_planner_interface::ResetCostmap > {
  static const char* value()
  {
    return "all_in_one_local_planner_interface/ResetCostmap";
  }

  static const char* value(const ::all_in_one_local_planner_interface::ResetCostmap&) { return value(); }
};


// service_traits::MD5Sum< ::all_in_one_local_planner_interface::ResetCostmapRequest> should match
// service_traits::MD5Sum< ::all_in_one_local_planner_interface::ResetCostmap >
template<>
struct MD5Sum< ::all_in_one_local_planner_interface::ResetCostmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_in_one_local_planner_interface::ResetCostmap >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::ResetCostmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_in_one_local_planner_interface::ResetCostmapRequest> should match
// service_traits::DataType< ::all_in_one_local_planner_interface::ResetCostmap >
template<>
struct DataType< ::all_in_one_local_planner_interface::ResetCostmapRequest>
{
  static const char* value()
  {
    return DataType< ::all_in_one_local_planner_interface::ResetCostmap >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::ResetCostmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_in_one_local_planner_interface::ResetCostmapResponse> should match
// service_traits::MD5Sum< ::all_in_one_local_planner_interface::ResetCostmap >
template<>
struct MD5Sum< ::all_in_one_local_planner_interface::ResetCostmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_in_one_local_planner_interface::ResetCostmap >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::ResetCostmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_in_one_local_planner_interface::ResetCostmapResponse> should match
// service_traits::DataType< ::all_in_one_local_planner_interface::ResetCostmap >
template<>
struct DataType< ::all_in_one_local_planner_interface::ResetCostmapResponse>
{
  static const char* value()
  {
    return DataType< ::all_in_one_local_planner_interface::ResetCostmap >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::ResetCostmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_RESETCOSTMAP_H
