// Generated by gencpp from file all_in_one_local_planner_interface/SetGlobalPlanRequest.msg
// DO NOT EDIT!


#ifndef ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLANREQUEST_H
#define ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLANREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace all_in_one_local_planner_interface
{
template <class ContainerAllocator>
struct SetGlobalPlanRequest_
{
  typedef SetGlobalPlanRequest_<ContainerAllocator> Type;

  SetGlobalPlanRequest_()
    : global_plan()  {
    }
  SetGlobalPlanRequest_(const ContainerAllocator& _alloc)
    : global_plan(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _global_plan_type;
  _global_plan_type global_plan;





  typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetGlobalPlanRequest_

typedef ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<std::allocator<void> > SetGlobalPlanRequest;

typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanRequest > SetGlobalPlanRequestPtr;
typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanRequest const> SetGlobalPlanRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator1> & lhs, const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator2> & rhs)
{
  return lhs.global_plan == rhs.global_plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator1> & lhs, const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_in_one_local_planner_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9dcfe9a844c48c8242f417ba3d5dc4c";
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9dcfe9a844c48c8ULL;
  static const uint64_t static_value2 = 0x242f417ba3d5dc4cULL;
};

template<class ContainerAllocator>
struct DataType< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_in_one_local_planner_interface/SetGlobalPlanRequest";
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request fields\n"
"# global path\n"
"nav_msgs/Path global_plan\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.global_plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGlobalPlanRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_in_one_local_planner_interface::SetGlobalPlanRequest_<ContainerAllocator>& v)
  {
    s << indent << "global_plan: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.global_plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLANREQUEST_H
