// Generated by gencpp from file all_in_one_local_planner_interface/SetGlobalPlan.msg
// DO NOT EDIT!


#ifndef ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLAN_H
#define ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLAN_H

#include <ros/service_traits.h>


#include <all_in_one_local_planner_interface/SetGlobalPlanRequest.h>
#include <all_in_one_local_planner_interface/SetGlobalPlanResponse.h>


namespace all_in_one_local_planner_interface
{

struct SetGlobalPlan
{

typedef SetGlobalPlanRequest Request;
typedef SetGlobalPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGlobalPlan
} // namespace all_in_one_local_planner_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlan > {
  static const char* value()
  {
    return "4764e75946282cd60aded40196d97e1e";
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlan&) { return value(); }
};

template<>
struct DataType< ::all_in_one_local_planner_interface::SetGlobalPlan > {
  static const char* value()
  {
    return "all_in_one_local_planner_interface/SetGlobalPlan";
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlan&) { return value(); }
};


// service_traits::MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlanRequest> should match
// service_traits::MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlan >
template<>
struct MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlan >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_in_one_local_planner_interface::SetGlobalPlanRequest> should match
// service_traits::DataType< ::all_in_one_local_planner_interface::SetGlobalPlan >
template<>
struct DataType< ::all_in_one_local_planner_interface::SetGlobalPlanRequest>
{
  static const char* value()
  {
    return DataType< ::all_in_one_local_planner_interface::SetGlobalPlan >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlanResponse> should match
// service_traits::MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlan >
template<>
struct MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlan >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_in_one_local_planner_interface::SetGlobalPlanResponse> should match
// service_traits::DataType< ::all_in_one_local_planner_interface::SetGlobalPlan >
template<>
struct DataType< ::all_in_one_local_planner_interface::SetGlobalPlanResponse>
{
  static const char* value()
  {
    return DataType< ::all_in_one_local_planner_interface::SetGlobalPlan >::value();
  }
  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLAN_H
