// Generated by gencpp from file all_in_one_local_planner_interface/SetGlobalPlanResponse.msg
// DO NOT EDIT!


#ifndef ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLANRESPONSE_H
#define ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_in_one_local_planner_interface
{
template <class ContainerAllocator>
struct SetGlobalPlanResponse_
{
  typedef SetGlobalPlanResponse_<ContainerAllocator> Type;

  SetGlobalPlanResponse_()
    : successful(false)  {
    }
  SetGlobalPlanResponse_(const ContainerAllocator& _alloc)
    : successful(false)  {
  (void)_alloc;
    }



   typedef uint8_t _successful_type;
  _successful_type successful;





  typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetGlobalPlanResponse_

typedef ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<std::allocator<void> > SetGlobalPlanResponse;

typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanResponse > SetGlobalPlanResponsePtr;
typedef boost::shared_ptr< ::all_in_one_local_planner_interface::SetGlobalPlanResponse const> SetGlobalPlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator1> & lhs, const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.successful == rhs.successful;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator1> & lhs, const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_in_one_local_planner_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ccdb752b565be6d250259ff3d0c7ea1";
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ccdb752b565be6dULL;
  static const uint64_t static_value2 = 0x250259ff3d0c7ea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_in_one_local_planner_interface/SetGlobalPlanResponse";
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response fields\n"
"bool successful\n"
;
  }

  static const char* value(const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.successful);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGlobalPlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_in_one_local_planner_interface::SetGlobalPlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "successful: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.successful);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_IN_ONE_LOCAL_PLANNER_INTERFACE_MESSAGE_SETGLOBALPLANRESPONSE_H
