(cl:defpackage plan_msgs-srv
  (:use )
  (:export
   "MAKEGLOBALPLAN"
   "<MAKEGLOBALPLAN-REQUEST>"
   "MAKEGLOBALPLAN-REQUEST"
   "<MAKEGLOBALPLAN-RESPONSE>"
   "MAKEGLOBALPLAN-RESPONSE"
   "SUBGOAL"
   "<SUBGOAL-REQUEST>"
   "SUBGOAL-REQUEST"
   "<SUBGOAL-RESPONSE>"
   "SUBGOAL-RESPONSE"
  ))

