// Generated by gencpp from file costmap_2d/ObstacleDump.msg
// DO NOT EDIT!


#ifndef COSTMAP_2D_MESSAGE_OBSTACLEDUMP_H
#define COSTMAP_2D_MESSAGE_OBSTACLEDUMP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace costmap_2d
{
template <class ContainerAllocator>
struct ObstacleDump_
{
  typedef ObstacleDump_<ContainerAllocator> Type;

  ObstacleDump_()
    : scans()  {
    }
  ObstacleDump_(const ContainerAllocator& _alloc)
    : scans(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::PointCloud2_<ContainerAllocator> >> _scans_type;
  _scans_type scans;





  typedef boost::shared_ptr< ::costmap_2d::ObstacleDump_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::costmap_2d::ObstacleDump_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleDump_

typedef ::costmap_2d::ObstacleDump_<std::allocator<void> > ObstacleDump;

typedef boost::shared_ptr< ::costmap_2d::ObstacleDump > ObstacleDumpPtr;
typedef boost::shared_ptr< ::costmap_2d::ObstacleDump const> ObstacleDumpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::costmap_2d::ObstacleDump_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::costmap_2d::ObstacleDump_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::costmap_2d::ObstacleDump_<ContainerAllocator1> & lhs, const ::costmap_2d::ObstacleDump_<ContainerAllocator2> & rhs)
{
  return lhs.scans == rhs.scans;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::costmap_2d::ObstacleDump_<ContainerAllocator1> & lhs, const ::costmap_2d::ObstacleDump_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace costmap_2d

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::costmap_2d::ObstacleDump_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::costmap_2d::ObstacleDump_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::costmap_2d::ObstacleDump_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f920aef0166f130f16d65011603c0109";
  }

  static const char* value(const ::costmap_2d::ObstacleDump_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf920aef0166f130fULL;
  static const uint64_t static_value2 = 0x16d65011603c0109ULL;
};

template<class ContainerAllocator>
struct DataType< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "costmap_2d/ObstacleDump";
  }

  static const char* value(const ::costmap_2d::ObstacleDump_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2[] scans\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::costmap_2d::ObstacleDump_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleDump_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::costmap_2d::ObstacleDump_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::costmap_2d::ObstacleDump_<ContainerAllocator>& v)
  {
    s << indent << "scans[]" << std::endl;
    for (size_t i = 0; i < v.scans.size(); ++i)
    {
      s << indent << "  scans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.scans[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COSTMAP_2D_MESSAGE_OBSTACLEDUMP_H
