log4j.logger.ros=FATAL
log4j.logger.ros.dynamic_gap.GapDetector=INFO
log4j.logger.ros.dynamic_gap.GapAssociator=INFO
log4j.logger.ros.dynamic_gap.GapEstimation=INFO
log4j.logger.ros.dynamic_gap.GapFeasibility=INFO
log4j.logger.ros.dynamic_gap.GapManipulator=INFO
log4j.logger.ros.dynamic_gap.GapTrajectoryGenerator=INFO
log4j.logger.ros.dynamic_gap.DynamicScanPropagator=INFO
log4j.logger.ros.dynamic_gap.TrajectoryEvaluator=INFO
log4j.logger.ros.dynamic_gap.Planner=INFO
log4j.logger.ros.dynamic_gap.DynamicGapPlanner=INFO
log4j.logger.ros.dynamic_gap.Controller=INFO
log4j.logger.ros.dynamic_gap.ScanPropagation=INFO
log4j.logger.ros.dynamic_gap.Gap=INFO
log4j.logger.ros.dynamic_gap.Scan=INFO
log4j.logger.ros.dynamic_gap.Timing=INFO
log4j.logger.ros.dynamic_gap.GapGoalPlacer=INFO
log4j.logger.ros.dynamic_gap.Visualizer=INFO
