log4j.logger.ros=FATAL
log4j.logger.ros.dynamic_gap.GapDetector=WARN
log4j.logger.ros.dynamic_gap.GapAssociator=INFO
log4j.logger.ros.dynamic_gap.GapPointAssociator=WARN
log4j.logger.ros.dynamic_gap.GapEstimation=WARN
log4j.logger.ros.dynamic_gap.GapPropagator=INFO
log4j.logger.ros.dynamic_gap.GapFeasibility=WARN
log4j.logger.ros.dynamic_gap.GapManipulator=WARN
log4j.logger.ros.dynamic_gap.GapTrajectoryGenerator=WARN
log4j.logger.ros.dynamic_gap.DynamicScanPropagator=WARN
log4j.logger.ros.dynamic_gap.TrajectoryEvaluator=WARN
log4j.logger.ros.dynamic_gap.Planner=INFO
log4j.logger.ros.dynamic_gap.DynamicGapPlanner=WARN
log4j.logger.ros.dynamic_gap.Controller=WARN
log4j.logger.ros.dynamic_gap.ScanPropagation=WARN
log4j.logger.ros.dynamic_gap.Gap=WARN
log4j.logger.ros.dynamic_gap.Scan=WARN
log4j.logger.ros.dynamic_gap.Timing=WARN
log4j.logger.ros.dynamic_gap.GapGoalPlacer=WARN
log4j.logger.ros.dynamic_gap.Visualizer=WARN
