log4j.logger.ros=FATAL

log4j.logger.ros.quad_gap.Planner=INFO
log4j.logger.ros.quad_gap.QuadGapPlanner=INFO
log4j.logger.ros.quad_gap.Timing=INFO
log4j.logger.ros.quad_gap.GapTrajectoryGenerator=INFO
