log4j.logger.ros=FATAL

log4j.logger.ros.quad_gap.Planner=INFO
log4j.logger.ros.quad_gap.QuadGapPlanner=WARN
log4j.logger.ros.quad_gap.Timing=WARN
log4j.logger.ros.quad_gap.Parameters=INFO

log4j.logger.ros.quad_gap.Scan=WARN
log4j.logger.ros.quad_gap.GapDetector=WARN
log4j.logger.ros.quad_gap.GapManipulator=INFO
log4j.logger.ros.quad_gap.GapGoalPlacer=INFO
log4j.logger.ros.quad_gap.GapTrajectoryGenerator=INFO
log4j.logger.ros.quad_gap.TrajectoryEvaluator=INFO
log4j.logger.ros.quad_gap.Controller=INFO
log4j.logger.ros.quad_gap.Visualizer=INFO
log4j.logger.ros.quad_gap.GapVisualizer=INFO
log4j.logger.ros.quad_gap.GoalVisualizer=INFO

log4j.logger.ros.quad_gap.Gap=INFO
log4j.logger.ros.quad_gap.Trajectory=WARN