log4j.logger.ros=FATAL

log4j.logger.ros.quad_gap.Planner=INFO
log4j.logger.ros.quad_gap.QuadGapPlanner=WARN
log4j.logger.ros.quad_gap.Timing=WARN
log4j.logger.ros.quad_gap.Parameters=INFO

log4j.logger.ros.quad_gap.Scan=WARN
log4j.logger.ros.quad_gap.GapDetector=WARN
log4j.logger.ros.quad_gap.GlobalPlanManager=WARN
log4j.logger.ros.quad_gap.GapManipulator=WARN
log4j.logger.ros.quad_gap.GapGoalPlacer=WARN
log4j.logger.ros.quad_gap.GapTrajectoryGenerator=WARN
log4j.logger.ros.quad_gap.TrajectoryEvaluator=WARN
log4j.logger.ros.quad_gap.RobotGeometryProcessor=WARN
log4j.logger.ros.quad_gap.Controller=WARN
log4j.logger.ros.quad_gap.Visualizer=WARN
log4j.logger.ros.quad_gap.GapVisualizer=WARN
log4j.logger.ros.quad_gap.GoalVisualizer=WARN

log4j.logger.ros.quad_gap.Gap=WARN
log4j.logger.ros.quad_gap.Trajectory=WARN
log4j.logger.ros.quad_gap.Utils=WARN