// Generated by gencpp from file flatland_msgs/DeleteModels.msg
// DO NOT EDIT!


#ifndef FLATLAND_MSGS_MESSAGE_DELETEMODELS_H
#define FLATLAND_MSGS_MESSAGE_DELETEMODELS_H

#include <ros/service_traits.h>


#include <flatland_msgs/DeleteModelsRequest.h>
#include <flatland_msgs/DeleteModelsResponse.h>


namespace flatland_msgs
{

struct DeleteModels
{

typedef DeleteModelsRequest Request;
typedef DeleteModelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteModels
} // namespace flatland_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flatland_msgs::DeleteModels > {
  static const char* value()
  {
    return "f17f88999ecf79098437ce7d74e28572";
  }

  static const char* value(const ::flatland_msgs::DeleteModels&) { return value(); }
};

template<>
struct DataType< ::flatland_msgs::DeleteModels > {
  static const char* value()
  {
    return "flatland_msgs/DeleteModels";
  }

  static const char* value(const ::flatland_msgs::DeleteModels&) { return value(); }
};


// service_traits::MD5Sum< ::flatland_msgs::DeleteModelsRequest> should match
// service_traits::MD5Sum< ::flatland_msgs::DeleteModels >
template<>
struct MD5Sum< ::flatland_msgs::DeleteModelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flatland_msgs::DeleteModels >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flatland_msgs::DeleteModelsRequest> should match
// service_traits::DataType< ::flatland_msgs::DeleteModels >
template<>
struct DataType< ::flatland_msgs::DeleteModelsRequest>
{
  static const char* value()
  {
    return DataType< ::flatland_msgs::DeleteModels >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flatland_msgs::DeleteModelsResponse> should match
// service_traits::MD5Sum< ::flatland_msgs::DeleteModels >
template<>
struct MD5Sum< ::flatland_msgs::DeleteModelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flatland_msgs::DeleteModels >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flatland_msgs::DeleteModelsResponse> should match
// service_traits::DataType< ::flatland_msgs::DeleteModels >
template<>
struct DataType< ::flatland_msgs::DeleteModelsResponse>
{
  static const char* value()
  {
    return DataType< ::flatland_msgs::DeleteModels >::value();
  }
  static const char* value(const ::flatland_msgs::DeleteModelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLATLAND_MSGS_MESSAGE_DELETEMODELS_H
