// Generated by gencpp from file pedsim_srvs/SpawnPed.msg
// DO NOT EDIT!


#ifndef PEDSIM_SRVS_MESSAGE_SPAWNPED_H
#define PEDSIM_SRVS_MESSAGE_SPAWNPED_H

#include <ros/service_traits.h>


#include <pedsim_srvs/SpawnPedRequest.h>
#include <pedsim_srvs/SpawnPedResponse.h>


namespace pedsim_srvs
{

struct SpawnPed
{

typedef SpawnPedRequest Request;
typedef SpawnPedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnPed
} // namespace pedsim_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pedsim_srvs::SpawnPed > {
  static const char* value()
  {
    return "dad6de4944e873f2a2559273751d6b69";
  }

  static const char* value(const ::pedsim_srvs::SpawnPed&) { return value(); }
};

template<>
struct DataType< ::pedsim_srvs::SpawnPed > {
  static const char* value()
  {
    return "pedsim_srvs/SpawnPed";
  }

  static const char* value(const ::pedsim_srvs::SpawnPed&) { return value(); }
};


// service_traits::MD5Sum< ::pedsim_srvs::SpawnPedRequest> should match
// service_traits::MD5Sum< ::pedsim_srvs::SpawnPed >
template<>
struct MD5Sum< ::pedsim_srvs::SpawnPedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pedsim_srvs::SpawnPed >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pedsim_srvs::SpawnPedRequest> should match
// service_traits::DataType< ::pedsim_srvs::SpawnPed >
template<>
struct DataType< ::pedsim_srvs::SpawnPedRequest>
{
  static const char* value()
  {
    return DataType< ::pedsim_srvs::SpawnPed >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pedsim_srvs::SpawnPedResponse> should match
// service_traits::MD5Sum< ::pedsim_srvs::SpawnPed >
template<>
struct MD5Sum< ::pedsim_srvs::SpawnPedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pedsim_srvs::SpawnPed >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pedsim_srvs::SpawnPedResponse> should match
// service_traits::DataType< ::pedsim_srvs::SpawnPed >
template<>
struct DataType< ::pedsim_srvs::SpawnPedResponse>
{
  static const char* value()
  {
    return DataType< ::pedsim_srvs::SpawnPed >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEDSIM_SRVS_MESSAGE_SPAWNPED_H
