// Generated by gencpp from file pedsim_srvs/SpawnPeds.msg
// DO NOT EDIT!


#ifndef PEDSIM_SRVS_MESSAGE_SPAWNPEDS_H
#define PEDSIM_SRVS_MESSAGE_SPAWNPEDS_H

#include <ros/service_traits.h>


#include <pedsim_srvs/SpawnPedsRequest.h>
#include <pedsim_srvs/SpawnPedsResponse.h>


namespace pedsim_srvs
{

struct SpawnPeds
{

typedef SpawnPedsRequest Request;
typedef SpawnPedsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnPeds
} // namespace pedsim_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pedsim_srvs::SpawnPeds > {
  static const char* value()
  {
    return "1a418c9646b48a91fc86313fb280ad3f";
  }

  static const char* value(const ::pedsim_srvs::SpawnPeds&) { return value(); }
};

template<>
struct DataType< ::pedsim_srvs::SpawnPeds > {
  static const char* value()
  {
    return "pedsim_srvs/SpawnPeds";
  }

  static const char* value(const ::pedsim_srvs::SpawnPeds&) { return value(); }
};


// service_traits::MD5Sum< ::pedsim_srvs::SpawnPedsRequest> should match
// service_traits::MD5Sum< ::pedsim_srvs::SpawnPeds >
template<>
struct MD5Sum< ::pedsim_srvs::SpawnPedsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pedsim_srvs::SpawnPeds >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pedsim_srvs::SpawnPedsRequest> should match
// service_traits::DataType< ::pedsim_srvs::SpawnPeds >
template<>
struct DataType< ::pedsim_srvs::SpawnPedsRequest>
{
  static const char* value()
  {
    return DataType< ::pedsim_srvs::SpawnPeds >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pedsim_srvs::SpawnPedsResponse> should match
// service_traits::MD5Sum< ::pedsim_srvs::SpawnPeds >
template<>
struct MD5Sum< ::pedsim_srvs::SpawnPedsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pedsim_srvs::SpawnPeds >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pedsim_srvs::SpawnPedsResponse> should match
// service_traits::DataType< ::pedsim_srvs::SpawnPeds >
template<>
struct DataType< ::pedsim_srvs::SpawnPedsResponse>
{
  static const char* value()
  {
    return DataType< ::pedsim_srvs::SpawnPeds >::value();
  }
  static const char* value(const ::pedsim_srvs::SpawnPedsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEDSIM_SRVS_MESSAGE_SPAWNPEDS_H
