// Generated by gencpp from file plan_msgs/MakeGlobalPlan.msg
// DO NOT EDIT!


#ifndef PLAN_MSGS_MESSAGE_MAKEGLOBALPLAN_H
#define PLAN_MSGS_MESSAGE_MAKEGLOBALPLAN_H

#include <ros/service_traits.h>


#include <plan_msgs/MakeGlobalPlanRequest.h>
#include <plan_msgs/MakeGlobalPlanResponse.h>


namespace plan_msgs
{

struct MakeGlobalPlan
{

typedef MakeGlobalPlanRequest Request;
typedef MakeGlobalPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakeGlobalPlan
} // namespace plan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plan_msgs::MakeGlobalPlan > {
  static const char* value()
  {
    return "421c8ea4d21c6c9db7054b4bbdf1e024";
  }

  static const char* value(const ::plan_msgs::MakeGlobalPlan&) { return value(); }
};

template<>
struct DataType< ::plan_msgs::MakeGlobalPlan > {
  static const char* value()
  {
    return "plan_msgs/MakeGlobalPlan";
  }

  static const char* value(const ::plan_msgs::MakeGlobalPlan&) { return value(); }
};


// service_traits::MD5Sum< ::plan_msgs::MakeGlobalPlanRequest> should match
// service_traits::MD5Sum< ::plan_msgs::MakeGlobalPlan >
template<>
struct MD5Sum< ::plan_msgs::MakeGlobalPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plan_msgs::MakeGlobalPlan >::value();
  }
  static const char* value(const ::plan_msgs::MakeGlobalPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_msgs::MakeGlobalPlanRequest> should match
// service_traits::DataType< ::plan_msgs::MakeGlobalPlan >
template<>
struct DataType< ::plan_msgs::MakeGlobalPlanRequest>
{
  static const char* value()
  {
    return DataType< ::plan_msgs::MakeGlobalPlan >::value();
  }
  static const char* value(const ::plan_msgs::MakeGlobalPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plan_msgs::MakeGlobalPlanResponse> should match
// service_traits::MD5Sum< ::plan_msgs::MakeGlobalPlan >
template<>
struct MD5Sum< ::plan_msgs::MakeGlobalPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plan_msgs::MakeGlobalPlan >::value();
  }
  static const char* value(const ::plan_msgs::MakeGlobalPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plan_msgs::MakeGlobalPlanResponse> should match
// service_traits::DataType< ::plan_msgs::MakeGlobalPlan >
template<>
struct DataType< ::plan_msgs::MakeGlobalPlanResponse>
{
  static const char* value()
  {
    return DataType< ::plan_msgs::MakeGlobalPlan >::value();
  }
  static const char* value(const ::plan_msgs::MakeGlobalPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAN_MSGS_MESSAGE_MAKEGLOBALPLAN_H
