(cl:defpackage cob_control_msgs-srv
  (:use )
  (:export
   "GETOBSTACLEDISTANCE"
   "<GETOBSTACLEDISTANCE-REQUEST>"
   "GETOBSTACLEDISTANCE-REQUEST"
   "<GETOBSTACLEDISTANCE-RESPONSE>"
   "GETOBSTACLEDISTANCE-RESPONSE"
  ))

