contestants:
  - name: dgap
    local_planner: dgap

  - name: rosnav
    local_planner: rosnav

  - name: rlca
    local_planner: rlca

  - name: trail
    local_planner: trail

  - name: mpc
    local_planner: mpc

  - name: teb
    local_planner: teb
  
  - name: dwa
    local_planner: dwa

  - name: pgap # what you want it to be called in logs
    local_planner: pgap # needs to match file naming
