(cl:defpackage cob_srvs-srv
  (:use )
  (:export
   "DOCK"
   "<DOCK-REQUEST>"
   "DOCK-REQUEST"
   "<DOCK-RESPONSE>"
   "DOCK-RESPONSE"
   "SETFLOAT"
   "<SETFLOAT-REQUEST>"
   "SETFLOAT-REQUEST"
   "<SETFLOAT-RESPONSE>"
   "SETFLOAT-RESPONSE"
   "SETINT"
   "<SETINT-REQUEST>"
   "SETINT-REQUEST"
   "<SETINT-RESPONSE>"
   "SETINT-RESPONSE"
   "SETSTRING"
   "<SETSTRING-REQUEST>"
   "SETSTRING-REQUEST"
   "<SETSTRING-RESPONSE>"
   "SETSTRING-RESPONSE"
  ))

