set(mpc_local_planner_msgs_MESSAGE_FILES "/home/az/github_may_messed_it_up_20250124arena_try_get_rel_vel_work/arena_ws/src/planners/mpc/mpc_local_planner_msgs/msg/StateFeedback.msg;/home/az/github_may_messed_it_up_20250124arena_try_get_rel_vel_work/arena_ws/src/planners/mpc/mpc_local_planner_msgs/msg/OptimalControlResult.msg")
set(mpc_local_planner_msgs_SERVICE_FILES "")
