stages:
  - name: empty_scenario_0
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_1.json

  - name: empty_scenario_1
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_2.json

  - name: empty_scenario_2
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_3.json

  - name: empty_scenario_3
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_4.json

  - name: empty_scenario_4
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_5.json

  - name: empty_scenario_5
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_6.json

  - name: empty_scenario_6
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_7.json

  - name: empty_scenario_7
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_8.json

  - name: empty_scenario_8
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: airport_49_9.json

  - name: empty_scenario_9
    episodes: 3
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario

    config:
      SCENARIO:
        file: airport_49_10.json