stages:
  - name: scenario1
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 7.json

  - name: scenario2
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 8.json

  - name: scenario1
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 9.json

  - name: scenario2
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 10.json