stages:
  - name: arena_hospital_large_scenario_0
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 0.json

  - name: arena_hospital_large_scenario_1
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 1.json

  - name: arena_hospital_large_scenario_2
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 2.json

  - name: arena_hospital_large_scenario_3
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 3.json

  - name: arena_hospital_large_scenario_4
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 4.json

  - name: arena_hospital_large_scenario_5
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 5.json         

  - name: arena_hospital_large_scenario_6
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 6.json

  - name: arena_hospital_large_scenario_7
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 7.json

  - name: arena_hospital_large_scenario_8
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 8.json

  - name: arena_hospital_large_scenario_9
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 9.json

  - name: arena_hospital_large_scenario_10
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 10.json

  - name: arena_hospital_large_scenario_11
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 11.json            

  - name: arena_hospital_large_scenario_12
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 12.json            

  - name: arena_hospital_large_scenario_13
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 13.json

  - name: arena_hospital_large_scenario_14
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 14.json

  - name: arena_hospital_large_scenario_15
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 15.json

  - name: arena_hospital_large_scenario_16
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 16.json

  - name: arena_hospital_large_scenario_17
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 17.json

  - name: arena_hospital_large_scenario_18
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 18.json         

  - name: arena_hospital_large_scenario_19
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 19.json

  - name: arena_hospital_large_scenario_20
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 20.json

  - name: arena_hospital_large_scenario_21
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 21.json

  - name: arena_hospital_large_scenario_22
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 22.json

  - name: arena_hospital_large_scenario_23
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 23.json

  - name: arena_hospital_large_scenario_24
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: 24.json            

  # - name: scenario_random
  #   episodes: 25
  #   robot: rto
  #   map: arena_hospital_large
  #   tm_robots: random
  #   tm_obstacles: random
  #   config:
  #     SCENARIO:
  #       file: default.json
  #     RANDOM:
  #       static:
  #         min: 0
  #         max: 0
  #         models: ["shelf"]
  #       interactive:
  #         min: 0
  #         max: 0
  #         models: ["shelf"]
  #       dynamic:
  #         min: 15
  #         max: 15
  #         models: ["actor1"]

  # - name: scenario_random
  #   episodes: 25
  #   robot: rto
  #   map: arena_hospital_large
  #   tm_robots: random
  #   tm_obstacles: random
  #   config:
  #     SCENARIO:
  #       file: default.json
  #     RANDOM:
  #       static:
  #         min: 0
  #         max: 0
  #         models: ["shelf"]
  #       interactive:
  #         min: 0
  #         max: 0
  #         models: ["shelf"]
  #       dynamic:
  #         min: 15
  #         max: 15
  #         models: ["actor1"]