stages:
  - name: CS3_approaching
    episodes: 1000
    robot: rto
    map: map_empty
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: CS3_approaching_custom.json