stages:
  - name: debug
    episodes: 20
    robot: rto
    map: map5
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: dense_v1.json #1agent_headon.json


# 1agent_headon_1unitaway
#2agent_headon_1unitup
# 1agent_perpendicular