stages:
  - name: static_test_0
    episodes: 1
    robot: rto
    map: arena_hospital_large
    tm_robots: scenario
    tm_obstacles: scenario
    config:
      SCENARIO:
        file: no_agents.json