; Auto-generated. Do not edit!


(cl:in-package mbf_msgs-msg)


;//! \htmlinclude GetInterPathFeedback.msg.html

(cl:defclass <GetInterPathFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GetInterPathFeedback (<GetInterPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetInterPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetInterPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mbf_msgs-msg:<GetInterPathFeedback> is deprecated: use mbf_msgs-msg:GetInterPathFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetInterPathFeedback>) ostream)
  "Serializes a message object of type '<GetInterPathFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetInterPathFeedback>) istream)
  "Deserializes a message object of type '<GetInterPathFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetInterPathFeedback>)))
  "Returns string type for a message object of type '<GetInterPathFeedback>"
  "mbf_msgs/GetInterPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetInterPathFeedback)))
  "Returns string type for a message object of type 'GetInterPathFeedback"
  "mbf_msgs/GetInterPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetInterPathFeedback>)))
  "Returns md5sum for a message object of type '<GetInterPathFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetInterPathFeedback)))
  "Returns md5sum for a message object of type 'GetInterPathFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetInterPathFeedback>)))
  "Returns full string definition for message of type '<GetInterPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetInterPathFeedback)))
  "Returns full string definition for message of type 'GetInterPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetInterPathFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetInterPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GetInterPathFeedback
))
