// Generated by gencpp from file training/StringResponse.msg
// DO NOT EDIT!


#ifndef TRAINING_MESSAGE_STRINGRESPONSE_H
#define TRAINING_MESSAGE_STRINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace training
{
template <class ContainerAllocator>
struct StringResponse_
{
  typedef StringResponse_<ContainerAllocator> Type;

  StringResponse_()
    : value()  {
    }
  StringResponse_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::training::StringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::training::StringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StringResponse_

typedef ::training::StringResponse_<std::allocator<void> > StringResponse;

typedef boost::shared_ptr< ::training::StringResponse > StringResponsePtr;
typedef boost::shared_ptr< ::training::StringResponse const> StringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::training::StringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::training::StringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::training::StringResponse_<ContainerAllocator1> & lhs, const ::training::StringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::training::StringResponse_<ContainerAllocator1> & lhs, const ::training::StringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace training

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::training::StringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::training::StringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::training::StringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::training::StringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::training::StringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::training::StringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::training::StringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64e58419496c7248b4ef25731f88b8c3";
  }

  static const char* value(const ::training::StringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64e58419496c7248ULL;
  static const uint64_t static_value2 = 0xb4ef25731f88b8c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::training::StringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "training/StringResponse";
  }

  static const char* value(const ::training::StringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::training::StringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string value\n"
;
  }

  static const char* value(const ::training::StringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::training::StringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::training::StringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::training::StringResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAINING_MESSAGE_STRINGRESPONSE_H
