PARAMETRIZED:
  file: default.xml
RANDOM:
  dynamic:
    max: 15
    min: 3
    models:
    - actor1
  interactive:
    max: 0
    min: 0
    models:
    - shelf
  seed: 913126910
  static:
    max: 10
    min: 5
    models:
    - shelf
SCENARIO:
  file: 0.json
STAGED:
  curriculum: default.yaml
  index: 0
episodes: -1
