// Generated by gencpp from file pedsim_msgs/AgentFeedback.msg
// DO NOT EDIT!


#ifndef PEDSIM_MSGS_MESSAGE_AGENTFEEDBACK_H
#define PEDSIM_MSGS_MESSAGE_AGENTFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace pedsim_msgs
{
template <class ContainerAllocator>
struct AgentFeedback_
{
  typedef AgentFeedback_<ContainerAllocator> Type;

  AgentFeedback_()
    : id()
    , force()
    , social_state()
    , vmax(0.0)  {
    }
  AgentFeedback_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , force(_alloc)
    , social_state(_alloc)
    , vmax(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _social_state_type;
  _social_state_type social_state;

   typedef double _vmax_type;
  _vmax_type vmax;





  typedef boost::shared_ptr< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AgentFeedback_

typedef ::pedsim_msgs::AgentFeedback_<std::allocator<void> > AgentFeedback;

typedef boost::shared_ptr< ::pedsim_msgs::AgentFeedback > AgentFeedbackPtr;
typedef boost::shared_ptr< ::pedsim_msgs::AgentFeedback const> AgentFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pedsim_msgs::AgentFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pedsim_msgs::AgentFeedback_<ContainerAllocator1> & lhs, const ::pedsim_msgs::AgentFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.force == rhs.force &&
    lhs.social_state == rhs.social_state &&
    lhs.vmax == rhs.vmax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pedsim_msgs::AgentFeedback_<ContainerAllocator1> & lhs, const ::pedsim_msgs::AgentFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pedsim_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16b4e5ba3766183aa44251605e9788a6";
  }

  static const char* value(const ::pedsim_msgs::AgentFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16b4e5ba3766183aULL;
  static const uint64_t static_value2 = 0xa44251605e9788a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pedsim_msgs/AgentFeedback";
  }

  static const char* value(const ::pedsim_msgs::AgentFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n"
"geometry_msgs/Vector3 force\n"
"string social_state\n"
"float64 vmax\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::pedsim_msgs::AgentFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.force);
      stream.next(m.social_state);
      stream.next(m.vmax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pedsim_msgs::AgentFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pedsim_msgs::AgentFeedback_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "social_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.social_state);
    s << indent << "vmax: ";
    Printer<double>::stream(s, indent + "  ", v.vmax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEDSIM_MSGS_MESSAGE_AGENTFEEDBACK_H
